// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_landingpage.cpp"
#include "EWIEGA46WW/moc_login.cpp"
#include "EWIEGA46WW/moc_signup.cpp"
#include "EWIEGA46WW/moc_usercovid19testresult.cpp"
#include "EWIEGA46WW/moc_userpage.cpp"
#include "EWIEGA46WW/moc_userprofile.cpp"
